-- AlterTable
ALTER TABLE "main_products" ALTER COLUMN "rating" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "rewiev" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "count" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "products" ALTER COLUMN "term" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "referral_bonus" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "dailyProfit" SET DEFAULT 0,
ALTER COLUMN "dailyProfit" SET DATA TYPE DOUBLE PRECISION;
